### ISSUE TITLE
FileNotFoundException thrown

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-duplicates-finder#4]
On one of my projects I'm getting:

```
java.io.FileNotFoundException: /Users/dnw/dev/xx/target/web/classes/main (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:220)
    at java.util.zip.ZipFile.<init>(ZipFile.java:150)
    at java.util.zip.ZipFile.<init>(ZipFile.java:164)
    at sbt.Using$$anonfun$zipFile$1.apply(Using.scala:82)
    at sbt.Using$$anonfun$zipFile$1.apply(Using.scala:82)
    at sbt.Using$$anon$2.openImpl(Using.scala:65)
    at sbt.OpenFile$class.open(Using.scala:43)
    at sbt.Using$$anon$2.open(Using.scala:64)
    at sbt.Using$$anon$2.open(Using.scala:64)
    at sbt.Using.apply(Using.scala:23)
    at com.typesafe.sbt.duplicates.ClasspathElement$.buildFromJar(ClasspathElement.scala:22)
    at com.typesafe.sbt.duplicates.ClasspathElement$.apply(ClasspathElement.scala:11)
    at com.typesafe.sbt.duplicates.Classpath$$anonfun$1.apply(Classpath.scala:9)
    at com.typesafe.sbt.duplicates.Classpath$$anonfun$1.apply(Classpath.scala:9)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.typesafe.sbt.duplicates.Classpath.<init>(Classpath.scala:9)
    at com.typesafe.sbt.duplicates.DuplicatesFinderPlugin$$anonfun$checkDuplicates0$1.apply(DuplicatesFinderPlugin.scala:26)
    at com.typesafe.sbt.duplicates.DuplicatesFinderPlugin$$anonfun$checkDuplicates0$1.apply(DuplicatesFinderPlugin.scala:23)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:checkDuplicates) java.io.FileNotFoundException: /Users/dnw/dev/xx/target/web/classes/main (No such file or directory)
```

It's a Play app, and it _might_ be related to my use of `disablePlugins(PlayLayoutPlugin)`, just because on another Play app that I have that doesn't do that it doesn't throw an exception.

**Comment by pdalpra** [comment]
Checking for existence before handling the classpath files can't really be a bad thing.
It already needed for the boot classpath after all.
